// File generated by FlutterFire CLI.
// This file should NOT be manually edited.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // The values below are examples only - the actual values will be populated
  // by the FlutterFire CLI when you run 'flutterfire configure'
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'GENERATED_API_KEY',
    appId: 'GENERATED_APP_ID',
    messagingSenderId: 'GENERATED_SENDER_ID',
    projectId: 'your-project-id',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'GENERATED_API_KEY',
    appId: 'GENERATED_APP_ID',
    messagingSenderId: 'GENERATED_SENDER_ID',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'GENERATED_API_KEY',
    appId: 'GENERATED_APP_ID',
    messagingSenderId: 'GENERATED_SENDER_ID',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: 'GENERATED_CLIENT_ID',
    iosBundleId: 'com.example.yourapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'GENERATED_API_KEY',
    appId: 'GENERATED_APP_ID',
    messagingSenderId: 'GENERATED_SENDER_ID',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: 'GENERATED_CLIENT_ID',
    iosBundleId: 'com.example.yourapp',
  );
}